name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "tony.akinyemi5@gmail.com"
        git config --global user.name "Tony Akinyemi"

    - name: Push to Hugging Face Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://huggingface.co/tony-901/Writing_Tool_Classifier hf_repo
        rsync -av --exclude='.git' ./ hf_repo/
        cd hf_repo
        git add .
        git commit -m "Sync from GitHub" || echo "No changes"
        git push https://tony-901:${HF_TOKEN}@huggingface.co/tony-901/Writing_Tool_Classifier main
